# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Gatitos Delight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gatitos Delight
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.5'
  pod 'Alamofire-SwiftyJSON', '~> 3.0'
  pod 'Kingfisher', '= 5.2'
end
